// Code generated by GALA transpiler. DO NOT EDIT.

package std

import "fmt"

//line std/try.gala:4

// Try represents a computation that may either result in a value of type T (Success)
// or a failure with an error (Failure). It provides a functional approach to error
// handling, similar to Scala's Try monad.
//
// Every instance of Try is either:
// - Success[T]: contains a successful value of type T
// - Failure[T]: contains an error
type Try[T any] struct {
	Value    Immutable[T]
	Err      Immutable[error]
	_variant uint8
}

const (
	_Try_Success uint8 = iota
	_Try_Failure
)

type Success[T any] struct {
}

func (_ Success[T]) Apply(Value T) Try[T] {
	return Try[T]{Value: NewImmutable(Value), _variant: _Try_Success}
}
func (_ Success[T]) Unapply(v Try[T]) Option[T] {
	if v._variant == _Try_Success {
		return Some[T]{}.Apply(v.Value.Get())
	}
	return None[T]{}.Apply()
}

type Failure[T any] struct {
}

func (_ Failure[T]) Apply(Err error) Try[T] {
	return Try[T]{Err: NewImmutable(Err), _variant: _Try_Failure}
}
func (_ Failure[T]) Unapply(v Try[T]) Option[error] {
	if v._variant == _Try_Failure {
		return Some[error]{}.Apply(v.Err.Get())
	}
	return None[error]{}.Apply()
}
func (s Try[T]) isSuccess() bool {
	return s._variant == _Try_Success
}
func (s Try[T]) isFailure() bool {
	return s._variant == _Try_Failure
}
func (s Try[T]) Copy() Try[T] {
	return Try[T]{Value: Copy(s.Value), Err: Copy(s.Err), _variant: Copy(s._variant)}
}
func (s Try[T]) Equal(other Try[T]) bool {
	return Equal(s.Value, other.Value) && Equal(s.Err, other.Err) && Equal(s._variant, other._variant)
}
func (s Try[T]) String() string {
	switch s._variant {
	case _Try_Success:
		return fmt.Sprintf("Success(%v)", s.Value.Get())
	case _Try_Failure:
		return fmt.Sprintf("Failure(%v)", s.Err.Get())
	default:
		return "Try(<unknown>)"
	}
}

type TryInstance interface {
	IsTry() bool
}

func (_ Try[T]) IsTry() bool {
	return true
}

//line std/try.gala:16

// IsSuccess returns true if this is a Success, false otherwise.
func (t Try[T]) IsSuccess() bool {
	return t.isSuccess()
}

//line std/try.gala:19

// IsFailure returns true if this is a Failure, false otherwise.
func (t Try[T]) IsFailure() bool {
	return t.isFailure()
}

//line std/try.gala:22

// Apply executes f and catches any panic, converting it to a Failure.
// This is the safe way to create a Try from a potentially panicking operation.
// Usage: Try[int](() => riskyDivide(10, 0))
func (t Try[T]) Apply(f func() T) Try[T] {
	return tryRecover[T](f)
}

//line std/try.gala:27

// Get returns the value if this is a Success, otherwise panics.
// On Failure it panics with the original error value (not a string), so a
// surrounding recover (e.g. a Future's panic capture) can recover the typed
// error unchanged rather than a wrapped message.
func (t Try[T]) Get() T {
//line std/try.gala:33
	if t.isFailure() {
//line std/try.gala:34
		panic(t.Err.Get())
	}
//line std/try.gala:36
	return t.Value.Get()
}

//line std/try.gala:38

// GetError returns the error if this is a Failure, otherwise panics.
func (t Try[T]) GetError() error {
//line std/try.gala:41
	if t.isSuccess() {
//line std/try.gala:42
		panic("Try.GetError on Success")
	}
//line std/try.gala:44
	return t.Err.Get()
}

//line std/try.gala:46

// GetOrElse returns the value if this is a Success, otherwise returns defaultValue.
func (t Try[T]) GetOrElse(defaultValue T) T {
//line std/try.gala:49
	if t.isSuccess() {
//line std/try.gala:50
		return t.Value.Get()
	}
//line std/try.gala:52
	return defaultValue
}

//line std/try.gala:54

// OrElse returns this Try if it is a Success, otherwise returns alternative.
func (t Try[T]) OrElse(alternative Try[T]) Try[T] {
//line std/try.gala:57
	if t.isSuccess() {
//line std/try.gala:58
		return t
	}
//line std/try.gala:60
	return alternative
}

//line std/try.gala:62

// OnSuccess executes a callback with the value if this is a Success,
// returns the original Try unchanged (for chaining).
func (t Try[T]) OnSuccess(f func(T)) Try[T] {
//line std/try.gala:66
	if t.isSuccess() {
//line std/try.gala:67
		f(t.Value.Get())
	}
//line std/try.gala:69
	return t
}

//line std/try.gala:71

// OnFailure executes a callback with the error if this is a Failure,
// returns the original Try unchanged (for chaining).
func (t Try[T]) OnFailure(f func(error)) Try[T] {
//line std/try.gala:75
	if t.isFailure() {
//line std/try.gala:76
		f(t.Err.Get())
	}
//line std/try.gala:78
	return t
}

//line std/try.gala:80

// ForEach applies the given procedure f to the value if this is a Success.
func (t Try[T]) ForEach(f func(T)) {
//line std/try.gala:83
	if t.isSuccess() {
//line std/try.gala:84
		f(t.Value.Get())
	}
}

//line std/try.gala:87

// Map applies the function f to the value if this is a Success.
// Returns a new Try containing the result. If f panics, the result is a Failure.
func Try_Map[U any, T any](t Try[T], f func(T) U) Try[U] {
//line std/try.gala:91
	if t.isFailure() {
//line std/try.gala:92
		return Failure[U]{}.Apply(t.Err.Get())
	}
//line std/try.gala:94
	return Success[U]{}.Apply(f(t.Value.Get()))
}

//line std/try.gala:96

// FlatMap applies the function f to the value if this is a Success.
// Returns the Try returned by f. If this is a Failure, returns the Failure.
func Try_FlatMap[U any, T any](t Try[T], f func(T) Try[U]) Try[U] {
//line std/try.gala:100
	if t.isFailure() {
//line std/try.gala:101
		return Failure[U]{}.Apply(t.Err.Get())
	}
//line std/try.gala:103
	return f(t.Value.Get())
}

//line std/try.gala:105

// Filter returns this Try if this is a Success and the predicate p returns true.
// Returns a Failure with NoSuchElementError if predicate returns false.
func (t Try[T]) Filter(p func(T) bool) Try[T] {
//line std/try.gala:109
	if t.isFailure() {
//line std/try.gala:110
		return t
	}
//line std/try.gala:112
	if p(t.Value.Get()) {
//line std/try.gala:113
		return t
	}
//line std/try.gala:115
	return Failure[T]{}.Apply(NoSuchElementError{Message: NewImmutable("Predicate does not hold")})
}

//line std/try.gala:117

// Recover applies the recovery function pf to the error if this is a Failure.
// Returns a Success with the recovered value. If pf panics, the result is still a Failure.
func (t Try[T]) Recover(pf func(error) T) Try[T] {
//line std/try.gala:121
	if t.isSuccess() {
//line std/try.gala:122
		return t
	}
//line std/try.gala:124
	return Success[T]{}.Apply(pf(t.Err.Get()))
}

//line std/try.gala:126

// RecoverWith applies the recovery function pf to the error if this is a Failure.
// Returns the Try returned by pf. If this is a Success, returns this Try.
func (t Try[T]) RecoverWith(pf func(error) Try[T]) Try[T] {
//line std/try.gala:130
	if t.isSuccess() {
//line std/try.gala:131
		return t
	}
//line std/try.gala:133
	return pf(t.Err.Get())
}

//line std/try.gala:135

// Transform applies s if this is a Success, f if this is a Failure.
// Both functions return a new Try.
func Try_Transform[U any, T any](t Try[T], s func(T) Try[U], f func(error) Try[U]) Try[U] {
//line std/try.gala:139
	if t.isSuccess() {
//line std/try.gala:140
		return s(t.Value.Get())
	}
//line std/try.gala:142
	return f(t.Err.Get())
}

//line std/try.gala:144

// Fold applies fa if this is a Failure, fs if this is a Success.
func Try_Fold[U any, T any](t Try[T], fa func(error) U, fs func(T) U) U {
//line std/try.gala:147
	if t.isSuccess() {
//line std/try.gala:148
		return fs(t.Value.Get())
	}
//line std/try.gala:150
	return fa(t.Err.Get())
}

//line std/try.gala:152

// ToOption returns Some(value) if this is a Success, None if this is a Failure.
func (t Try[T]) ToOption() Option[T] {
//line std/try.gala:155
	if t.isSuccess() {
//line std/try.gala:156
		return Some[T]{}.Apply(t.Value.Get())
	}
//line std/try.gala:158
	return None[T]{}.Apply()
}

//line std/try.gala:160

// ToEither returns Right(value) if this is a Success, Left(error) if this is a Failure.
func (t Try[T]) ToEither() Either[error, T] {
//line std/try.gala:163
	if t.isSuccess() {
//line std/try.gala:164
		return Right[error, T]{}.Apply(t.Value.Get())
	}
//line std/try.gala:166
	return Left[error, T]{}.Apply(t.Err.Get())
}

//line std/try.gala:168

// FromOption creates a Try from an Option.
// Returns Success if the Option is Some, Failure with NoSuchElementError if None.
func FromOption[T any](o Option[T]) Try[T] {
	return func(obj Option[T]) Try[T] {
		{
			_tmp_1 := Some[T]{}.Unapply(obj)
			_tmp_2 := _tmp_1.IsDefined()
			var _tmp_3 T
			if _tmp_2 {
				_tmp_3 = _tmp_1.Get()
			}
			_ = _tmp_3
			v := _tmp_3
			if _tmp_2 {
				return Success[T]{}.Apply(v)
			} else {
				_tmp_4 := None[T]{}.Unapply(obj)
				if _tmp_4 {
					return Failure[T]{}.Apply(NoSuchElementError{Message: NewImmutable("Option is None")})
				} else {
					panic("unreachable")
				}
			}
		}
	}(o)
}

//line std/try.gala:175

// FromEitherError creates a Try from an Either[error, T].
// Returns Success if Right, Failure if Left.
func FromEitherError[T any](e Either[error, T]) Try[T] {
	return func(obj Either[error, T]) Try[T] {
		{
			_tmp_5 := Right[error, T]{}.Unapply(obj)
			_tmp_6 := _tmp_5.IsDefined()
			var _tmp_7 T
			if _tmp_6 {
				_tmp_7 = _tmp_5.Get()
			}
			_ = _tmp_7
			v := _tmp_7
			if _tmp_6 {
				return Success[T]{}.Apply(v)
			} else {
				_tmp_8 := Left[error, T]{}.Unapply(obj)
				_tmp_9 := _tmp_8.IsDefined()
				var _tmp_10 error
				if _tmp_9 {
					_tmp_10 = _tmp_8.Get()
				}
				_ = _tmp_10
				err := _tmp_10
				if _tmp_9 {
					return Failure[T]{}.Apply(err)
				} else {
					panic("unreachable")
				}
			}
		}
	}(e)
}

//line std/try.gala:182

// TryApply executes f and catches any panic, converting it to a Failure.
// Returns Success[T] with the result if f completes normally.
// Returns Failure[T] with the panic value as error if f panics.
func TryApply[T any](f func() T) Try[T] {
	return tryRecover[T](f)
}

//line std/try.gala:186

// PanicStack returns the stack trace of the panic that err came from, taken
// when Try (or TryApply) recovered it: Some(stack) for the error of a Failure
// made from a panic — or an error wrapping one — and None for any other error,
// such as the one in FromError(err). The frames point at .gala source lines.
//
// The stack is not part of the error's message or equality: Error() is the
// panic's own message, and Failures of the same panic value are equal.
//
// Usage:
//
//	Try(handle(req)).OnFailure((err) => {
//	    Println(s"request failed: $err")
//	    PanicStack(err).ForEach((stack) => Println(stack))
//	})
func PanicStack(err error) Option[string] {
	return panicStackOf(err)
}

//line std/try.gala:202

// Void represents the absence of a meaningful value, similar to Scala's Void.
// Used as the type parameter for Try[Void] when converting Go error returns.
type Void struct {
}

func (s Void) Copy() Void {
	return Void{}
}
func (s Void) Equal(other Void) bool {
	return true
}
func (s Void) Unapply(v any) bool {
	if _, ok := v.(Void); ok {
		return true
	}
	if _, ok := v.(*Void); ok {
		return true
	}
	return false
}

//line std/try.gala:205

// FromError converts a Go error return into a Try[Void].
// Returns Success[Void] if err is nil, Failure[Void] otherwise.
// `Try(goCall())` over a Go call returning only an error means the same.
//
// A Go call returning (T, error) needs no conversion: used as a value it
// already is a Try[T].
//
// Usage:
//
//	FromError(conn.Close())                        // Try[Void]
//	FromError(sb.ListenAndServe(addr))              // Try[Void]
//	FromError(sb.ListenAndServe(addr)).OnFailure((err) => Println(s"error: $err"))
func FromError(err error) Try[Void] {
//line std/try.gala:219
	if err != nil {
//line std/try.gala:220
		return Failure[Void]{}.Apply(err)
	}
//line std/try.gala:222
	return Success[Void]{}.Apply(Void{})
}

//line std/try.gala:225

// GoTry turns the two results of a Go call returning `(T, error)` into a
// Try: Failure(err) when err is non-nil, Success(value) otherwise.
//
// A Go call used as a value is converted with it automatically, so
// `os.ReadFile(path)` already is a `Try[[]byte]`; GoTry names that
// conversion for code that holds the two results separately.
func GoTry[T any](value T, err error) Try[T] {
//line std/try.gala:233
	if err != nil {
//line std/try.gala:234
		return Failure[T]{}.Apply(err)
	}
//line std/try.gala:236
	return Success[T]{}.Apply(value)
}

//line std/try.gala:238

// GoTry2 turns the results of a Go call returning 2 values and a
// trailing error into a Try of a Tuple: Failure(err) when err is non-nil,
// Success((a, b)) otherwise.
func GoTry2[A any, B any](a A, b B, err error) Try[Tuple[A, B]] {
//line std/try.gala:243
	if err != nil {
//line std/try.gala:244
		return Failure[Tuple[A, B]]{}.Apply(err)
	}
//line std/try.gala:246
	return Success[Tuple[A, B]]{}.Apply(Tuple[A, B]{V1: NewImmutable(a), V2: NewImmutable(b)})
}

//line std/try.gala:248

// GoTry3 turns the results of a Go call returning 3 values and a
// trailing error into a Try of a Tuple3: Failure(err) when err is non-nil,
// Success((a, b, c)) otherwise.
func GoTry3[A any, B any, C any](a A, b B, c C, err error) Try[Tuple3[A, B, C]] {
//line std/try.gala:253
	if err != nil {
//line std/try.gala:254
		return Failure[Tuple3[A, B, C]]{}.Apply(err)
	}
//line std/try.gala:256
	return Success[Tuple3[A, B, C]]{}.Apply(Tuple3[A, B, C]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c)})
}

//line std/try.gala:258

// GoTry4 turns the results of a Go call returning 4 values and a
// trailing error into a Try of a Tuple4: Failure(err) when err is non-nil,
// Success((a, b, c, d)) otherwise.
func GoTry4[A any, B any, C any, D any](a A, b B, c C, d D, err error) Try[Tuple4[A, B, C, D]] {
//line std/try.gala:263
	if err != nil {
//line std/try.gala:264
		return Failure[Tuple4[A, B, C, D]]{}.Apply(err)
	}
//line std/try.gala:266
	return Success[Tuple4[A, B, C, D]]{}.Apply(Tuple4[A, B, C, D]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d)})
}

//line std/try.gala:268

// GoTry5 turns the results of a Go call returning 5 values and a
// trailing error into a Try of a Tuple5: Failure(err) when err is non-nil,
// Success((a, b, c, d, e)) otherwise.
func GoTry5[A any, B any, C any, D any, E any](a A, b B, c C, d D, e E, err error) Try[Tuple5[A, B, C, D, E]] {
//line std/try.gala:273
	if err != nil {
//line std/try.gala:274
		return Failure[Tuple5[A, B, C, D, E]]{}.Apply(err)
	}
//line std/try.gala:276
	return Success[Tuple5[A, B, C, D, E]]{}.Apply(Tuple5[A, B, C, D, E]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d), V5: NewImmutable(e)})
}

//line std/try.gala:278

// GoTry6 turns the results of a Go call returning 6 values and a
// trailing error into a Try of a Tuple6: Failure(err) when err is non-nil,
// Success((a, b, c, d, e, f)) otherwise.
func GoTry6[A any, B any, C any, D any, E any, F any](a A, b B, c C, d D, e E, f F, err error) Try[Tuple6[A, B, C, D, E, F]] {
//line std/try.gala:283
	if err != nil {
//line std/try.gala:284
		return Failure[Tuple6[A, B, C, D, E, F]]{}.Apply(err)
	}
//line std/try.gala:286
	return Success[Tuple6[A, B, C, D, E, F]]{}.Apply(Tuple6[A, B, C, D, E, F]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d), V5: NewImmutable(e), V6: NewImmutable(f)})
}

//line std/try.gala:288

// GoTry7 turns the results of a Go call returning 7 values and a
// trailing error into a Try of a Tuple7: Failure(err) when err is non-nil,
// Success((a, b, c, d, e, f, g)) otherwise.
func GoTry7[A any, B any, C any, D any, E any, F any, G any](a A, b B, c C, d D, e E, f F, g G, err error) Try[Tuple7[A, B, C, D, E, F, G]] {
//line std/try.gala:293
	if err != nil {
//line std/try.gala:294
		return Failure[Tuple7[A, B, C, D, E, F, G]]{}.Apply(err)
	}
//line std/try.gala:296
	return Success[Tuple7[A, B, C, D, E, F, G]]{}.Apply(Tuple7[A, B, C, D, E, F, G]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d), V5: NewImmutable(e), V6: NewImmutable(f), V7: NewImmutable(g)})
}

//line std/try.gala:298

// GoTry8 turns the results of a Go call returning 8 values and a
// trailing error into a Try of a Tuple8: Failure(err) when err is non-nil,
// Success((a, b, c, d, e, f, g, h)) otherwise.
func GoTry8[A any, B any, C any, D any, E any, F any, G any, H any](a A, b B, c C, d D, e E, f F, g G, h H, err error) Try[Tuple8[A, B, C, D, E, F, G, H]] {
//line std/try.gala:303
	if err != nil {
//line std/try.gala:304
		return Failure[Tuple8[A, B, C, D, E, F, G, H]]{}.Apply(err)
	}
//line std/try.gala:306
	return Success[Tuple8[A, B, C, D, E, F, G, H]]{}.Apply(Tuple8[A, B, C, D, E, F, G, H]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d), V5: NewImmutable(e), V6: NewImmutable(f), V7: NewImmutable(g), V8: NewImmutable(h)})
}

//line std/try.gala:308

// GoTry9 turns the results of a Go call returning 9 values and a
// trailing error into a Try of a Tuple9: Failure(err) when err is non-nil,
// Success((a, b, c, d, e, f, g, h, i)) otherwise.
func GoTry9[A any, B any, C any, D any, E any, F any, G any, H any, I any](a A, b B, c C, d D, e E, f F, g G, h H, i I, err error) Try[Tuple9[A, B, C, D, E, F, G, H, I]] {
//line std/try.gala:313
	if err != nil {
//line std/try.gala:314
		return Failure[Tuple9[A, B, C, D, E, F, G, H, I]]{}.Apply(err)
	}
//line std/try.gala:316
	return Success[Tuple9[A, B, C, D, E, F, G, H, I]]{}.Apply(Tuple9[A, B, C, D, E, F, G, H, I]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d), V5: NewImmutable(e), V6: NewImmutable(f), V7: NewImmutable(g), V8: NewImmutable(h), V9: NewImmutable(i)})
}

//line std/try.gala:318

// GoTry10 turns the results of a Go call returning 10 values and a
// trailing error into a Try of a Tuple10: Failure(err) when err is non-nil,
// Success((a, b, c, d, e, f, g, h, i, j)) otherwise.
func GoTry10[A any, B any, C any, D any, E any, F any, G any, H any, I any, J any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, err error) Try[Tuple10[A, B, C, D, E, F, G, H, I, J]] {
//line std/try.gala:323
	if err != nil {
//line std/try.gala:324
		return Failure[Tuple10[A, B, C, D, E, F, G, H, I, J]]{}.Apply(err)
	}
//line std/try.gala:326
	return Success[Tuple10[A, B, C, D, E, F, G, H, I, J]]{}.Apply(Tuple10[A, B, C, D, E, F, G, H, I, J]{V1: NewImmutable(a), V2: NewImmutable(b), V3: NewImmutable(c), V4: NewImmutable(d), V5: NewImmutable(e), V6: NewImmutable(f), V7: NewImmutable(g), V8: NewImmutable(h), V9: NewImmutable(i), V10: NewImmutable(j)})
}
